# nameOverride:  # Overrides the default app name
# fullnameOverride:  # Overrides the default fully qualified app name
# commonLabels:  # Extra labels to apply to all chart resources

# Configure one or more Queues
queues:
#   - name: volcano
#     weight: 1
#     capability:
#       cpu: 2

# Configure the webhook manager
webhookManager:
  image: 
    # Use a custom image registry, not docker hub
    # registry: wolf.cira.colostate.edu:444
    registry:
    # The image repository
    repository: volcanosh/vc-webhook-manager
    # The image tag (defaults to the application version in Chart.yaml)
    tag:
    pullPolicy: IfNotPresent
  # Maybe later, after I've dealt with the issue in github
  # managedNamespaces:
  #   - 'volcano'
  # ignoredNamespaces:  # a list of namespaces to be ingored by the webhook-manager
  #   - 'argocd'
  #   - 'cert-manager'
  #   - 'default'
  #   - 'ingress-nginx'
  #   - 'jupyterhub'
  #   - 'kube-node-lease'
  #   - 'kube-public'
  #   - 'kube-system'
  #   - 'longhorn-system'
  #   - 'monitoring'

# Configure the controllers
controllers:
  image:
    # Use a custom image registry, not docker hub
    # registry: wolf.cira.colostate.edu:444
    registry:
    # The image repository
    repository: volcanosh/vc-controller-manager
    # The image tag (defaults to the application version in Chart.yaml)
    tag:
    pullPolicy: IfNotPresent

# Configure the scheduler
scheduler:
  image:
    # Use a custom image registry, not docker hub
    # registry: wolf.cira.colostate.edu:444
    registry:
    # The image repository
    repository: volcanosh/vc-scheduler
    # The image tag (defaults to the application version in Chart.yaml)
    tag:
    pullPolicy: IfNotPresent
