# nameOverride:  # Overrides the default app name
# fullnameOverride:  # Overrides the default fully qualified app name
# commonLabels:  # Extra labels to apply to all chart resources

webhookManager:
  image: 
    registry: wolf.cira.colostate.edu:444
    repository: volcanosh/vc-webhook-manager
    tag: v1.5.1
    pullPolicy: Always
  # managedNamespaces:
  #   - 'volcano'
  # ignoredNamespaces:  # a list of namespaces to be ingored by the webhook-manager
  #   - 'argocd'
  #   - 'cert-manager'
  #   - 'default'
  #   - 'ingress-nginx'
  #   - 'jupyterhub'
  #   - 'kube-node-lease'
  #   - 'kube-public'
  #   - 'kube-system'
  #   - 'longhorn-system'
  #   - 'monitoring'

controllers:
  image: 
    registry: wolf.cira.colostate.edu:444
    repository: volcanosh/vc-controller-manager
    tag: v1.5.1
    pullPolicy: Always

scheduler:
  image: 
    registry: wolf.cira.colostate.edu:444
    repository: volcanosh/vc-scheduler
    tag: v1.5.1
    pullPolicy: Always
