apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "volcano.name" . }}-scheduler
  labels:
    {{- include "volcano.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "volcano.name" . }}-scheduler
subjects:
- kind: ServiceAccount
  name: {{ include "volcano.name" . }}-scheduler
  namespace: {{ .Release.Namespace }}-system
