apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "volcano.name" . }}-scheduler
  labels:
    {{- include "volcano.labels" . | indent 4 }}
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - get
  - list
  - watch
  - delete
- apiGroups:
  - batch.volcano.sh
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - update
  - delete
- apiGroups:
  - batch.volcano.sh
  resources:
  - jobs/status
  verbs:
  - update
  - patch
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - list
  - watch
  - update
  - patch
- apiGroups:
  - ''
  resources:
  - pods
  - pods/status
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - bind
  - updateStatus
  - delete
- apiGroups:
  - ''
  resources:
  - pods/binding
  verbs:
  - create
- apiGroups:
  - ''
  resources:
  - persistentvolumeclaims
  verbs:
  - list
  - watch
  - update
- apiGroups:
  - ''
  resources:
  - persistentvolumes
  verbs:
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - namespaces
  verbs:
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - resourcequotas
  verbs:
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - nodes
  verbs:
  - list
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  - csinodes
  - csidrivers
  - csistoragecapacities
  verbs:
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - list
  - watch
- apiGroups:
  - scheduling.k8s.io
  resources:
  - priorityclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scheduling.incubator.k8s.io
  - scheduling.volcano.sh
  resources:
  - queues
  verbs:
  - get
  - list
  - watch
  - create
  - delete
- apiGroups:
  - scheduling.incubator.k8s.io
  - scheduling.volcano.sh
  resources:
  - podgroups
  verbs:
  - list
  - watch
  - update
- apiGroups:
  - nodeinfo.volcano.sh
  resources:
  - numatopologies
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
  - create
  - delete
  - update
