apiVersion: v1
kind: Service
metadata:
  name: {{ include "volcano.name" . }}-scheduler
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: admission-init
    {{- include "volcano.labels" . | indent 4 }}
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '8080'
    prometheus.io/scrape: 'true'
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/component: scheduler
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIP
