apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "volcano.name" . }}-controllers
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: controller
    {{- include "volcano.labels" . | indent 4 }}
  namespace: volcano-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: controllers
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controllers
        {{- include "volcano.labels" . | indent 8 }}
    spec:
      containers:
      - args:
        - --logtostderr
        - --enable-healthz=true
        - -v=4
        - 2>&1
        {{- with .Values.controllers.image }}
        image: "{{- if .registry -}}{{ .registry }}/{{- end -}}{{ .repository }}{{- if ((.digest)) -}} @{{ .digest }}{{- else -}}:{{ default $.Chart.AppVersion .tag }} {{- end -}}"
        imagePullPolicy: {{ .pullPolicy | default "IfNotPresent" }}
        {{- end }}
        name: controllers
      priorityClassName: system-cluster-critical
      serviceAccount: {{ include "volcano.name" . }}-controllers
