apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "volcano.name" . }}-controllers
  namespace: {{ .Release.Namespace }}-system
  labels:
    {{- include "volcano.labels" . | indent 4 }}
