apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "volcano.name" . }}-admission-init
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: admission-init
    {{- include "volcano.labels" . | indent 4 }}
spec:
  backoffLimit: 3
  template:
    spec:
      containers:
      - command:
        - ./gen-admission-secret.sh
        - --service
        - {{ include "volcano.name" . }}-admission
        - --namespace
        - {{ .Release.Namespace }}
        - --secret
        - {{ include "volcano.name" . }}-admission
        {{- with .Values.webhookManager.image }}
        image: {{ include "volcano.image" . }}{{ include "volcano.imageTag" . | default (printf ":%s" $.Chart.AppVersion ) }} 
        imagePullPolicy: {{ .pullPolicy | default "IfNotPresent" }}
        {{- end }}
        name: main
      priorityClassName: system-cluster-critical
      restartPolicy: Never
      serviceAccountName: {{ include "volcano.name" . }}-admission
