apiVersion: v1
kind: Service
metadata:
  name: {{ include "volcano.name" . }}-admission
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: admission-init
    {{- include "volcano.labels" . | indent 4 }}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app.kubernetes.io/component: admission
    app.kubernetes.io/instance: {{ .Release.Name }}
  sessionAffinity: None
